import {useEffect} from 'react'
import {Grid, Typography} from "@material-ui/core";
import {ScrollUp} from '../../utils/helper';
import {Helmet} from "react-helmet";

const Policy = () => {
    useEffect(() => {
        ScrollUp();
    }, [])
    return (
        <Grid
            container
            spacing={3}
            direction="column"
            justify="center"
            alignItems="center"
            style={{textAlign: 'justify'}}
        >
            <Helmet>
                <title>
                    Rent Finder - Houses, Flats and Apartments for rent
                </title>
                <meta name="description" content="rental platform with many Houses, Flats and Apartments for rent.
                rent finder provide a centralized platform for finding or renting apartments, homes and condos in your city. " />
                <meta name="keywords" content="Rent finder Houses, Flat and Apartments for rent"/>
            </Helmet>
            <Grid item xs={9}>
                <h1>Privacy Policy</h1><br/>
                <p>
                    We are RentFinder.de ("Us", "We" or "Our"), we operate a website that allows people to list or
                    locate apartments, houses or other real estate for rent online within the territory of the Federal
                    Republic of Germany.
                </p><br/>
                <p>
                    We are strongly committed to protecting your privacy and complying with your choices. Both Personal
                    and non-personal information collected is safeguarded according to the highest privacy and data
                    protection standards adopted worldwide.
                </p><br/>
                <p>
                    We use your data to provide and improve our Services. By using our Services, you agree to the
                    collection and use of information in accordance with this policy. Unless otherwise defined in this
                    Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms of Use.
                    Our Terms of use (“Terms”) govern all use of our Service and together with the Privacy Policy
                    constitutes your agreement with us (“Agreement”).
                </p><br/>
                <p>
                    We know that you care how information about you is used and shared and we appreciate your trust in
                    us to do that carefully and sensibly. This Privacy Policy describes how we collect and process your
                    personal information through our website.
                </p><br/>
                <p>
                    Our Privacy Policy ("Privacy Policy") helps explain our data practices, including the information we
                    process to provide our Services.
                </p><br/>
                <p>
                    This Policy was last reviewed on 01.06.2021 and will be reviewed again 01.12.2021
                </p><br/>
                <ol>
                    <li><strong>DEFINITIONS</strong>
                        <ol>
                            <li>
                                <strong>SERVICE </strong>means the “Rentfinder.de” Website operated by
                                RentFinder.de.
                            </li>
                            <li>
                                <strong>PERSONAL DATA </strong>means data about a living individual who can be
                                identified from that data (or from those and other information either in our
                                possession
                                or likely to come into our possession).
                            </li>
                            <li>
                                <strong>USAGE DATA </strong>is data collected automatically either generated by the
                                use
                                of Service or from Service infrastructure itself (for example, the duration of a
                                page
                                visit).
                            </li>
                            <li>
                                <strong>COOKIES </strong>are small files stored on your device (computer or mobile
                                device).
                            </li>
                            <li>
                                <strong>DATA CONTROLLER </strong>means a natural or legal person who (either alone
                                or
                                jointly or in common with other persons) determines the purposes for which and the
                                manner in which any personal data are, or are to be, processed. For the purpose of
                                this
                                Privacy Policy, we are a Data Controller of your data.
                            </li>
                            <li>
                                <strong>DATA PROCESSORS </strong>(OR SERVICE PROVIDERS) means any natural or legal
                                person who processes the data on behalf of the Data Controller. We may use the
                                services
                                of various Service Providers in order to process your data more effectively.
                            </li>
                            <li>
                                <strong>DATA SUBJECT </strong>is any living individual who is the subject of
                                Personal
                                Data.
                            </li>
                            <li>
                                <strong>THE USER </strong>is the individual using our Service. The User corresponds
                                to
                                the Data
                                Subject, who is the subject of Personal Data. This includes anyone who is browsing
                                our
                                portal.
                            </li>
                        </ol>
                    </li>
                    <br/>

                    <li><strong>INFORMATION COLLECTION AND USE</strong>
                        <p>We collect several different types of information for various purposes to provide and
                            improve our Service to you.</p><br/>
                    </li>

                    <li><strong>TYPES OF DATA COLLECTED</strong>

                        <ol type="I">
                            <li><strong>Personal Data</strong>
                                <p>
                                    While using our Service, we may ask you to provide us with certain personally
                                    identifiable information that can be used to contact or identify you (“Personal
                                    Data”). Personally, identifiable information may include, but is not limited to:
                                </p>
                                <ol>
                                    <li>
                                        Email address
                                    </li>
                                    <li>
                                        First name and last name
                                    </li>
                                    <li>
                                        Phone number
                                    </li>
                                    <li>
                                        Address, Country, State, Province, ZIP/Postal code, City
                                    </li>
                                    <li>
                                        Usage Data
                                    </li>
                                </ol>
                                <br/>
                                <p>
                                    We may use your Personal Data to contact you with newsletters, marketing or
                                    promotional materials and other information that may be of interest to you. You
                                    may
                                    opt out of receiving any, or all, of these communications from us by following
                                    the
                                    unsubscribe link.
                                </p>
                            </li>
                            <br/>

                            <li><strong>Location Data</strong>
                                <p>
                                    We may use and store information about your location if you give us permission
                                    to do
                                    so (“Location Data”). We use this data to provide features of our Service, to
                                    improve and customize our Service.
                                </p><br/>
                                <p>
                                    You can enable or disable location services when you use our Service at any time
                                    by
                                    way of your device settings.
                                </p>
                            </li>
                            <br/>

                            <li><strong>Usage Data</strong>
                                <p>
                                    We also collect information that your browser sends whenever you visit our
                                    Service
                                    or when you access Service by or through any device (“Usage Data”).
                                </p><br/>
                                <p>
                                    This Usage Data may include information such as your computer’s Internet
                                    Protocol
                                    address (e.g. IP address), browser type, browser version, the pages of our
                                    Service
                                    that you visit, the time and date of your visit, the time spent on those pages,
                                    unique device identifiers and other diagnostic data.
                                </p><br/>
                                <p>
                                    When you access Service with a device, this Usage Data may include information
                                    such
                                    as the type of device you use, your device unique ID, the IP address of your
                                    device,
                                    your device operating system, the type of Internet browser you use, unique
                                    device
                                    identifiers and other diagnostic data.
                                </p>
                            </li>
                            <br/>

                            <li><strong>Tracking Cookies Data</strong>
                                <p>
                                    We use cookies and similar tracking technologies to track the activity on our
                                    Service and we hold certain information.
                                </p><br/>
                                <p>
                                    Cookies are files with a small amount of data which may include an anonymous
                                    unique
                                    identifier. Cookies are sent to your browser from a website and stored on your
                                    device. Other tracking technologies are also used such as beacons, tags and
                                    scripts
                                    to collect
                                    and track information and to improve and analyze our Service.
                                </p><br/>
                                <p>
                                    You can instruct your browser to refuse all cookies or to indicate when a cookie
                                    is
                                    being sent. However, if you do not accept cookies, you may not be able to use
                                    some
                                    portions of our Service.
                                </p><br/>
                                <p><u>Examples of Cookies we use:</u>
                                    <ol>
                                        <li>Session Cookies: We use Session Cookies to operate our Service.</li>
                                        <li>Preference Cookies: We use Preference Cookies to remember your
                                            preferences
                                            and various settings.
                                        </li>
                                        <li>Security Cookies: We use Security Cookies for security purposes.</li>
                                    </ol>
                                </p>
                            </li>
                            <br/>

                            <li><strong>USE OF DATA</strong>
                                <p>
                                    RentFinder.de uses the collected data for various purposes:
                                </p>
                                <ol>
                                    <li>To provide and maintain our Service;</li>
                                    <li>To notify you about changes to our Service;</li>
                                    <li>To allow you to participate in interactive features of our Service when you
                                        choose to do so
                                    </li>
                                    <li>To provide customer support;</li>
                                    <li>To gather analysis or valuable information so that we can improve our
                                        Service;
                                    </li>
                                    <li>To fulfil any other purpose for which you provide it;</li>
                                    <li>To carry out our obligations and enforce our rights arising from any
                                        contracts
                                        entered into between you and us, including for billing and collection;
                                    </li>
                                    <li>To provide you with notices about your account and/or subscription,
                                        including
                                        expiration and renewal notices, email-instructions, etc.;
                                    </li>
                                    <li>To provide you with news, special offers and general information about other
                                        goods, services and events which we offer that are similar to those that you
                                        have already purchased or enquired about unless you have opted not to
                                        receive
                                        such information;
                                    </li>
                                    <li>In any other way we may describe when you provide the information;</li>
                                    <li>For any other purpose with your consent.</li>
                                </ol>
                            </li>
                            <br/>

                            <li><strong>RETENTION OF DATA</strong>
                                <p>
                                    We will retain your Personal Data only for as long as is necessary for the purposes
                                    set out in this Privacy Policy. We will retain and use your Personal Data to the
                                    extent necessary to comply with our legal obligations (for example, if we are
                                    required to retain your data to comply with applicable laws), resolve disputes, and
                                    enforce our legal agreements and policies.
                                </p>
                                <p>
                                    We will also retain Usage Data for internal analysis purposes. Usage Data is
                                    generally retained for a shorter period, except when this data is used to strengthen
                                    the security or to improve the functionality of our Service, or we are legally
                                    obligated to retain this data for longer time periods.
                                </p>
                            </li>
                            <br/>

                            <li><strong>DISCLOSURE OF DATA</strong>
                                <p>
                                    We may disclose personal information that we collect, or you provide:
                                </p>
                                <ol>
                                    <li>Business Transaction
                                        <p>
                                            If we or our subsidiaries are involved in a merger, acquisition or asset
                                            sale, your Personal Data may be transferred.
                                        </p>
                                    </li>
                                    <li>
                                        Other cases
                                        <p>We may disclose your information also:
                                            <ol>
                                                <li>To our subsidiaries and affiliates;</li>
                                                <li>To fulfil the purpose for which you provide it;</li>
                                                <li> For any other purpose disclosed by us when you provide the
                                                    information;
                                                </li>
                                                <li> If we believe disclosure is necessary or appropriate to protect
                                                    the
                                                    rights, property, or safety of our customers, or others.
                                                </li>
                                            </ol>
                                        </p>
                                    </li>
                                </ol>
                            </li>
                            <br/>

                            <li><strong>SECURITY OF DATA</strong>
                                <p>
                                    The security of your data is important to us but remember that no method of
                                    transmission over the Internet or method of electronic storage is 100% secure.
                                    While
                                    we strive to use commercially acceptable means to protect your Personal Data, we
                                    cannot guarantee its absolute security. We use SSL encryption. You can recognize
                                    such encrypted connections by the prefix https: // in the address line of your
                                    browser.
                                </p>
                            </li>
                            <br/>

                            <li><strong>OUR COMMITMENT</strong>
                                <p>
                                    Your Information will not be shared, rented or sold to any third party. We give
                                    you
                                    the possibility to control the information that you shared with us (opt-out), We
                                    are
                                    committed to processing data in accordance with its responsibilities under the
                                    GDPR.
                                </p>
                            </li>
                            <br/>

                            <li><strong>TRANSPARENCY</strong>
                                <p>
                                    We will always explain clearly what data we’re collecting about you and why. We
                                    will
                                    only collect data we need to:
                                </p><br/>
                                <ol>
                                    <li>Business Transaction
                                        Give you a better experience
                                    </li>
                                    <li>
                                        Improve our services
                                    </li>
                                    <li>
                                        Fulfil our responsibilities as a public service.
                                    </li>
                                </ol>
                            </li>
                            <br/>

                            <li><strong>EU AND EEA USERS RIGHTS</strong>
                                <p>
                                    If you are habitually located in the European Union or European Economic Area,
                                    you
                                    have the right to access, rectify, download or erase your information, as well
                                    as
                                    the right to restrict and object to certain processing of your information.
                                    While
                                    some of these rights apply generally, certain rights apply only in certain
                                    limited
                                    circumstances. We Describe these rights below:
                                </p><br/>
                                <p>
                                    You have the right to access your personal data and, if necessary, have it
                                    amended
                                    or deleted or restricted, in certain instances, you may have the right to the
                                    portability of your data, you can also ask us to not send marketing
                                    communications
                                    and not to use your personal data when we carry out profiling for direct
                                    marketing
                                    purposes. you can opt out receiving email newsletters and other marketing
                                    communications by following the opt-out instruments provided to you in those
                                    emails.
                                    Transactional account messages will be unaffected if you opt-out from marketing
                                    communications.
                                </p>
                            </li>
                            <br/>

                            <li><strong>SERVICE PROVIDERS</strong>
                                <p>
                                    We may in the near future employ third party companies and individuals to
                                    facilitate
                                    our Service (“Service Providers”), provide Service on our behalf, perform
                                    Service-related services or assist us in analysing how our Service is used.
                                </p><br/>
                                <p>
                                    These third parties have access to your Personal Data only to perform these
                                    tasks on
                                    our behalf and are obligated not to disclose or use it for any other purpose.
                                </p>
                            </li>
                            <br/>

                            <li><strong>ANALYTICS</strong>
                                <p>
                                    We use Google Analytics to monitor and analyse the use of our Service.
                                </p>
                            </li>
                            <br/>

                            <li><strong>CHILDREN’S PRIVACY</strong>
                                <p>
                                    Our Services are not intended for use by children under the age of 18 (“Child”
                                    or
                                    “Children”).
                                </p><br/>
                                <p>
                                    We do not knowingly collect personally identifiable information from Children
                                    under
                                    18 (Eighteen). If you become aware that a Child has provided us with Personal
                                    Data,
                                    please contact us. If we become aware that we have collected Personal Data from
                                    Children without verification of parental consent, we take steps to remove that
                                    information from our servers.
                                </p>
                            </li>
                            <br/>

                            <li><strong>CHANGES TO THIS PRIVACY POLICY</strong>
                                <p>
                                    We may update our Privacy Policy from time to time. We will notify you of any
                                    changes by posting the new Privacy Policy on this page.

                                </p><br/>
                                <p>
                                    We will let you know via email and/or a prominent notice on our Service, prior
                                    to
                                    the change becoming effective and update “effective date” at the top of this
                                    Privacy
                                    Policy.
                                </p><br/>
                                <p>You are advised to review this Privacy Policy periodically for any changes.</p>
                                <p>Changes to this Privacy Policy are effective when they are posted on this
                                    page.</p>
                            </li>
                            <br/>

                            <li><strong>ENFORCEMENT OF POLICY</strong>
                                <p>
                                    If for some reason you believe RentFinder.de has not adhered to these
                                    principles,
                                    please notify us and we will do our best to promptly make corrections.
                                </p>
                            </li>
                            <br/>

                            <li><strong>CONTACT US</strong>
                                <p>
                                    If you have any questions about this Privacy Policy, the practices of this site,
                                    or
                                    your dealings with this site, please contact us
                                    at: <strong>info@rent-finder.de</strong>
                                </p>
                            </li>
                        </ol>
                    </li>
                </ol>

            </Grid>
        </Grid>
    );
};

export default Policy;
